[server]
    address = "0.0.0.0"
    port = 8090
    hasPprof = true # 是否启用pprof查看性能
    hasSwagger = true # 是否展示swagger api
    runMode = "debug" # debug/release

[mysql]
    host = "127.0.0.1"
    port = 3306
    dbname = "mammoth"
    user = "root"
    password = "123456"
    maxOpenConns = 50
    maxIdleConns = 6
    #db_table_prefix = "mammoth"


[log]
    fileName = "run.log" # 日志输出文件路径
    maxBackups = 3 # 最多保留备份个数
    maxSize = 300  #文件大小 单位兆字节
    toFile = true # 是同时输出控制台和文件
    isJson = false # 是否按JSON格式输出
    level = "debug" # 日志级别